### ISSUE TITLE
Ars Magica potion issues

### ISSUE THREAD

**Issue by woodhoda** [Cuppycake/Mech-and-Magic#101]
Apparently some potion ids are mixing up and conflicting... when I made the spell Self, Leap, and Featherfall, instead I got self, Chrono anchor (end tier of self, supposed to restore you after death), and legendary Mana Regen. The legendary mana regen seems to apply, but the chrono anchor I think is featherfall without the slowfall.

**Comment by woodhoda** [comment]
This is on the server as a side note, singleplayer doesn't seem to have this issue.

**Comment by Cuppycake** [comment]
On our server or your own?

**Comment by woodhoda** [comment]
The server offered by the pack itself. Also flammable replaces Ars Magica's Haste (movement speed boost) I don't know what it's actual effects are though. Because the effects seem to be mixing up with names too. Sorry trying to lend a hand, hopefully it's not too much a problem that I do some testing myself.

**Comment by Cuppycake** [comment]
Ill look into it tomorrow on my day off but Im almost certain its going to be an issue with Thermos, the custom forge jar we use to run plugins and there wont be much we can do about it. But Ill comb over the logs and the configs.
