### ISSUE TITLE
Journeymap not working in latest update

### ISSUE THREAD

**Issue by TriffidDK** [Cuppycake/Mech-and-Magic#102]
Journeymap dissapeared in the current version of M&M. It was set to install as optional map mod and the jar is in the mod folder. but mod is not available in game.
Reinstall did not work.

**Comment by TriffidDK** [comment]
As far as I can see the latest pack version has a 1.8 version of journeymap. Manually replaced it with the 1.7.10 which worked ;)

**Comment by Cuppycake** [comment]
Figures. He didnt label anything in curse so the ATL auto updater grabbed a 1.8. Will fix shortly.
