### ISSUE TITLE
Journeymap

### ISSUE THREAD

**Issue by Matthew7991** [Cuppycake/Mech-and-Magic#103]
In the Version Mech-and-Magic 2.2.23 the Journeymap version is for 1.8.9 and not for 1.7.10

**Comment by Cuppycake** [comment]
Good thing there is already a hot fix out for this.  Around 19 hours before you posted lol.

**Comment by Cuppycake** [comment]
Good thing there is already a hot fix out for this.  Around 19 hours before you posted lol.

**Comment by Matthew7991** [comment]
good that there were no update news

**Comment by Cuppycake** [comment]
Except there was and your launcher prompts you to update
