### ISSUE TITLE
Death Protection Poppet Witchery not working

### ISSUE THREAD

**Issue by UNcageDYetINoG** [Cuppycake/Mech-and-Magic#109]
Soooo I tried performing the Rite of Infusion on myself using the Spirit of Otherwhere and NORMALLY you need some kind of means to prevent the death that follows if you're not prepared. So I made a death protection poppet ( the item you need to prevent that death) and I still killed me and didn't give me the infusion. So i made ANOTHER death protection poppet (very expensive btw lol) and tried it again this time leaving it on a poppet shelf aaaand it still killed me...a resolution would be awesome otherwise we can't enjoy that part of the mod lol, thanks!

**Comment by Cuppycake** [comment]
Is this in SSP or on the official server?

**Comment by UNcageDYetINoG** [comment]
This is on the official server

**Comment by Cuppycake** [comment]
Some time ago we disabled some Witcher functions to prevent grieving and pvp.  This may be working as intended.  Could you replicate this in single player to verify?

**Comment by UNcageDYetINoG** [comment]
Yes it works in single player. Maybe you could at least enable the spirit of otherwhere on the server? it's main use is for teleportation; It gets hectic having to recall to the spawn point and travel all the way back to your base lol but it's entirely up to you guys; thank you for the help.

**Comment by Cuppycake** [comment]
Some things aren't disabled but simply not compatible with the custom jars we use to run the server with plug-ins for anti grief and the like.  Alternatively their are several other mods for teleportation. I'll check into it.
