### ISSUE TITLE
Gravestone's in someone else's lot

### ISSUE THREAD

**Issue by UNcageDYetINoG** [Cuppycake/Mech-and-Magic#110]
It's also a bit of a bummer when you're exploring, die, and it turns out your gravestone is in someone elses claim...so first off how is it that I could get my stuff back besides ask the owner ( who is never on)?

**Comment by Cuppycake** [comment]
Owner has a life outside of the server.  Try not to poke around people's claims.

**Comment by UNcageDYetINoG** [comment]
I wasn't by any means it just so happens I was just outside of mine hunting skeletons and died on someone else's, I didn't have any reason to poke around someone else's.  I just thought maybe someone could help get my stuff back. Thank you anyway.

**Comment by UNcageDYetINoG** [comment]
Also (and I'm so sorry to keep bothering you) but is there a list or something showing what's been disabled and what hasn't just so I know what NOT to do in certain mods, you know? Ty.
