### ISSUE TITLE
Crash to launcher when using bc pipes or AE2 seeds

### ISSUE THREAD

**Issue by Keirgarth** [Cuppycake/Mech-and-Magic#114]
Have run into a couple of issues with the mod pack sorry to say. When I start laying out buildcraft pipes the game crashes to the launcher. When I log back in I have enough time to delete the pipes before it crashes me out again. Once the pipes are deleted everything is fine again.

The same thing happens when I put seeds for AE2 into a pool of water, game crashes to launcher.

Any suggestions?

System is 2 months old and is custom built i7 5930k, 32Gb RAM, 1Tb Samsung 850 EVO SSD, 2 GTX 1080's in SLI with the HBM bridge. 

Currently all drivers and java 64bit are up to date on Windows 10 Pro 64

**Comment by Cuppycake** [comment]
I suggest providing a crash report,  first.

**Comment by Keirgarth** [comment]
Been a while Cuppycake, which file is it?

**Comment by Cuppycake** [comment]
Click open folder in the instance box on the ATLauncher. Open the folder labeled crash-reports and copy the contents of the latest document to pastebin.com and leave a link here.

**Comment by Keirgarth** [comment]
After spending a bit of time trying to find the link to copy so you could see the crash log I decided to look through the log myself. It appears that my crash is because Optifine and EnderIO don't get along very well. I have disabled Optifine and it appears to be working ok now.
