### ISSUE TITLE
Mekanism Basic Logistical Transporter Crash

### ISSUE THREAD

**Issue by Gsdigger** [Cuppycake/Mech-and-Magic#119]
So I accidentally  placed a basic logistical transporter next to my bed while I was right clicking to sleep. Every time I try to brake it with any tool or even my hand it crashes the game after I have reached 9%( I can see that in Waila). You can stop breaking it before it reaches 9% and it won't crash. The building its in, is a generated roguelike dungeon and its placed on the top floor (I haven't destroyed any of the blocks around it.). I tried using a sticky piston to brake it and nothing happened.If you place blocks around it nothing happens. It is adjacent to a bed and a polished granite block. I tried using a configurator tool and it can change the color without crashing, so its really weird. Every time the game crashes the world gets messed up a bit (for example pipes are missing, machines are turned around, chests are missing etc.). I am playing on the beta-3 of 1.10.2 Minecraft and the Launchers version is 3.2.3.1.Also i am playing on a Laptop, a Sony Vaio SV1521V!EW. Here are some crash reports, I hope I provided enough info to help solve this issue.

[crash-2016-11-19_17.49.34-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/601747/crash-2016-11-19_17.49.34-client.txt)
[crash-2016-11-19_18.14.14-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/601746/crash-2016-11-19_18.14.14-client.txt)
[crash-2016-11-19_18.15.05-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/601748/crash-2016-11-19_18.15.05-client.txt)
[crash-2016-11-19_18.16.01-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/601745/crash-2016-11-19_18.16.01-client.txt)
[crash-2016-11-19_23.08.59-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/601744/crash-2016-11-19_23.08.59-client.txt)
[crash-2016-11-19_16.58.19-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/601749/crash-2016-11-19_16.58.19-client.txt)

I placed another basic logistical transporter next to it and the same thing happens. Here is the crash report for that.
[crash-2016-11-19_23.43.17-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/601751/crash-2016-11-19_23.43.17-client.txt)

**Comment by Gsdigger** [comment]
I am going to replace the pipes with air so that I can continue playing without it bugging me, but I will keep a backup of the world in case it is useful.

**Comment by Cuppycake** [comment]
This is the best bug report I've ever received lol. Bravo. Ill look into it and forward what I can to the author.
Can you break the bed without crashing? Can you break the bed or all blocks touching any face of the machine and then break it without crashing?

**Comment by Gsdigger** [comment]
I will try.

**Comment by Gsdigger** [comment]
So, i tried breaking all blocks adjacent to the pipe and i didn't crash, but the problem persisted. I also tried putting a pipe down next to a vanilla chest to see what would happen, but I could remove the pipe without crashing at 9%. I could change the pull/push side of it. there are the crash reports for both of the cases:
[crash-2016-11-21_17.48.05-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/604068/crash-2016-11-21_17.48.05-client.txt)
[crash-2016-11-20_23.30.43-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/604067/crash-2016-11-20_23.30.43-client.txt)

**Comment by Cuppycake** [comment]
Should be fixed in our next update.

**Comment by Cuppycake** [comment]
@Gsdigger try to reproduce with beta4 please

**Comment by Gsdigger** [comment]
FIXED!
