### ISSUE TITLE
Shift clicking the + sign under a recepie with items that have health crashing the game.

### ISSUE THREAD

**Issue by Gsdigger** [Cuppycake/Mech-and-Magic#120]
So I tried to make an armored jetpack and an upgraded energy cube from Mekanism and the game just froze the moment I clicked the + sign under the recepie. The game wouldn't close on its own so there are no crash reports, but I noticed the top-left item would appear in the crafting grid of the vanilla crafting table before the game froze. I haven't yet tried using any other crafting grid or recepies from other mods.
When I just clicked the button, not shift clicked, it worked. The jetpack had no fuel at the time of the upgrade, but the energy cube was about 3/4 full although that doesn't seem to make a difference. There is a crash report from around the time of the event, but I don't know if it has anything to do with our problem. Here it is:

[crash-2016-11-20_18.55.13-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/604093/crash-2016-11-20_18.55.13-client.txt)

**Comment by Gsdigger** [comment]
I misspelled something in the original post. I meant to say that the game wouldn't close on its own. I updated it now.

**Comment by Cuppycake** [comment]
@Gsdigger try to reproduce with beta4 please

**Comment by Gsdigger** [comment]
FIXED!

**Comment by Gsdigger** [comment]
It just happened again while I was trying to make an advanced energy cell.(In a crafting station.)
Crash report this time:

[crash-2016-11-23_21.03.31-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/609769/crash-2016-11-23_21.03.31-client.txt)

**Comment by Cuppycake** [comment]
I'll send this up to Mekanism GitHub. Nothing we can do about it as far as the log tells me. 

Thanks
