### ISSUE TITLE
Funky UI in Minecraft start screen.

### ISSUE THREAD

**Issue by Gsdigger** [Cuppycake/Mech-and-Magic#121]
When Minecraft launches and you have the options of Forever Alone, Multiplayer etc. , when I hover over Multiplayer, Discord or Patreon the background image will turn black till I move my mouse off of it. This issue is not persistent, it will happen 90% of the time though. Sorry for opening so many issues, but since we started lets finish it. 
Update 1: After a bit I figured out that those tree options are the ones with the pop out text, when you hover over them.

**Comment by Cuppycake** [comment]
Alright thanks. It has to do with the resolution of the users monitor but I can't really find a good fix. Probably just gonna ditch the tool tip like pop outs.

**Comment by Gsdigger** [comment]
Ok, should I close the issue?

**Comment by Gsdigger** [comment]
I leave the decision making part of this issue to you, so I am going to close the issue.
