### ISSUE TITLE
Pack Crashing

### ISSUE THREAD

**Issue by SOCKPUPP3TS** [Cuppycake/Mech-and-Magic#122]
Not sure if this is the right place for it or not but i am having trouble launching the pack from the AT launcher. I have played the server before and got a pretty good base established before taking a break. All PC parts and programs remained the same. Crash report can be found here: http://pastebin.com/MPe1QpLB

**Comment by Cuppycake** [comment]
What version of the modpack?

**Comment by SOCKPUPP3TS** [comment]
1.10.2-Beta4.1

**Comment by Cuppycake** [comment]
update to beta 5 and try to reproduce. If problem persists try without optifine installed.

**Comment by SOCKPUPP3TS** [comment]
Neither worked, i have the crash report from when i tried it without optifine and updated to beta 5
http://pastebin.com/isQy90gj
