### ISSUE TITLE
Moving when in game crashing the game.

### ISSUE THREAD

**Issue by Gsdigger** [Cuppycake/Mech-and-Magic#123]
So I am still running Beta4.1 from before and today I wanted to play after 2 days, but the moment I enter the world and start moving I crash.
I can move my head around and see the world, but when I move the game crashes.
The game acts like normal till the moment I move. I don't know if I can interact with chests etc., but I will try.
Here are the crash reports:

[crash-2016-11-26_10.43.54-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/614229/crash-2016-11-26_10.43.54-client.txt)
[crash-2016-11-26_11.11.24-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/614231/crash-2016-11-26_11.11.24-client.txt)
[crash-2016-11-26_14.48.40-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/614230/crash-2016-11-26_14.48.40-client.txt)

**Comment by Gsdigger** [comment]
I have some more information about the crashes.
I can interact with objects, sort chests etc., but then when I open the crafting grid and move the advanced energy cell in the middle and start putting those blue alloys around it (still trying to make the damn ultimate energy cell) the grid disappears (but the darker background remains) and I crash.

Crash report:
[crash-2016-11-27_12.13.37-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/614635/crash-2016-11-27_12.13.37-client.txt)

**Comment by Cuppycake** [comment]
Can you try removing optifine and reproducing?

**Comment by Gsdigger** [comment]
It works fine without optifine. What should I do now, play without it or ... ?

**Comment by Cuppycake** [comment]
Figured.  Optifine is breaking rail craft and ender io textures right now.  Play without for the time being until we update.
