### ISSUE TITLE
Tin Ore not spawning in worlds.

### ISSUE THREAD

**Issue by bagaznal** [Cuppycake/Mech-and-Magic#131]
So me and my brother loaded your pack and made a server and so on, but for some reason Tin didn't spawn at all in our world. I've checked the respective Y levels for its spawn and saw nothing. I'm not sure if this is intentional, because (I think) Immersive Engineering can dig up tin without it being present, but I'm not sure. I just thought I should point this out because I have no clue if it's intentional.

Also, we created this server yesterday. We downloaded and updated the pack and then because there wasn't a server download for 1.0.6 yet when we got it, I just deleted the old server mod folder and dragged the mod folder from instances over to the server. Only thing I can think would be that the configs changed the ore spawn to work.

**Comment by Cuppycake** [comment]
I assume you found tin?
