### ISSUE TITLE
Server Crashes Once Player Joins (World Specific)

### ISSUE THREAD

**Issue by Shoopdasoup** [Cuppycake/Mech-and-Magic#134]
I am running a private server with friends, but the world has entered a state where it crashes once a player joins, there must be something wrong with the chunks.

http://pastebin.com/YF8EJD8d

Here is the crash report. Let me know if more information is needed.

**Comment by Cuppycake** [comment]
Definitely an Applied Energistics issue. Are you editing any mods in the pack? Ask your friends what they were last doing with AE when the server crashes. It shouldn't be any player crashing, only ones in the effected chunk.

**Comment by Shoopdasoup** [comment]
I haven't messed with any of the mods in the pack, and we have an ME system set up. The last thing we were doing on the server was breeding chickens with hatchery. Players in spawn chunks also crash, but not only do the players crash, the server crashes as well.

**Comment by Cuppycake** [comment]
Your best bet at this moment is to remove applied energistics 2, run the server,  stop it,  readd AE2,  run the server.

**Comment by Shoopdasoup** [comment]
I tried that, but at this point, all of the blocks are corrupted and nothing that I have placed down is the same anymore.

**Comment by Cuppycake** [comment]
I have nothing further for you then.  Removing the mod and restaeting should completely remove any AE corruption.  A complete wipe might be needed.  I highly suggest some method of backing up your server map.
