### ISSUE TITLE
Botania fall damage

### ISSUE THREAD

**Issue by TriffidDK** [Cuppycake/Mech-and-Magic#18]
Botania fall damage protection in form of Soujourners sash and globetrotters sash is broken. Seems like no protection at all. Expect my death counter to skyrocket ;) (as I do the opposite)

**Comment by Cuppycake** [comment]
Was this corrected in the last update?

**Comment by TriffidDK** [comment]
haven't had time to get on until now due to work. No, its not corrected.. using a BM sigil of elemental affinity instead :/

**Comment by Cuppycake** [comment]
Ive been informed the mod changed and that they now need mana to function.

**Comment by TriffidDK** [comment]
Well I always have mana on me since I use Botania armor...
