### ISSUE TITLE
bc floodgate

### ISSUE THREAD

**Issue by NalyKalZul** [Cuppycake/Mech-and-Magic#28]
was running a bc floodgate for my thermalilly setup,and the block looks rather odd at this stage and refused to work,took it down for now to see if the crash rate stay impacted as it currently is.

also since the last crash as of 1:17 pm servertime i lost all my Dimensional Transceiver channels,public ones are gone and so are the private ones i set up.
(edit)
and prior to the crash set up a new ender-thermic pump becuase i noticed the first one i placed was gone(nether reset?),which is also gone now after the crash but the resources i used are gone also which include a DC's to pipe the energy in and lava out.

**Comment by Cuppycake** [comment]
I'm not sure what if any bug you are trying to report.

**Comment by NalyKalZul** [comment]
i figured you reset the nether by hand when i first found out the pump was gone,which a few others players confirmed you planned to do later that day.
but i lost 2 more pumps during the time after because of crashes during the day that reset the nether again and again,and i lost all resources for every setup.
i don't know if those crashes caused a partial reset or a full one.
al i know is the ender thermic pump chunk loads itself,and something doesn't seem to like that.

and regarding to the bc floodgate i used for my enderlilly setup,the block changed texture to that of a broken bc block,so i took it out as precaution

**Comment by Cuppycake** [comment]
Yes the nether periodically resets along with the End and the Mining Dimension. Signs at spawn warn against building in them. Item loss on resets is on the player. 

Crashes will almost always cause some sort of roll back. Hence our Auto Saves every 20 minutes to limit the damage done. 

Chicken Chunks is not in the modpack

The BC floodgate may appear broken along with many other BC blocks as this is an entirely new version of buildcraft, Buildcraft 7. It bring a ton of changes and almost all blocks have been re textured.
