### ISSUE TITLE
Mod Recommendation

### ISSUE THREAD

**Issue by Moldycheez** [Cuppycake/Mech-and-Magic#29]
I have played this modpack for about 2 weeks and I thoroughly enjoy it. However, I was missing some mods that I enjoy. If possible, I would recommend adding Witchery, Minechem, Dense Ores, and Metallurgy 4.

Thanks!

**Comment by Cuppycake** [comment]
Well I am very glad to hear that you enjoy the pack. We are constantly working on it and tweaking it to be more fun for the players. 

Witchery is something I waffle with often but have yet to have the time to play with it myself to make up my mind. This is a mod that could most likely be added in the future.

Minechem is horribly unstable and I have no interest in adding it to the pack. 

Denseores is another I sometimes ponder but I believe with the amount of ways their are to double, and up to 5x multiply, ores in the pack it just seems cheap to me. 

Matallurgy is another mod that I feel has most of its mechanics already handled by several other mods in the pack already. Redundancy is something I try to avoid.

Thanks for your input! The pack itself is not pushing around 160 mods at any time so we are a little picky as to what gets added these days. Trying to keep the pack playable to as many people as possible.
