### ISSUE TITLE
Iron Bucket Duplication

### ISSUE THREAD

**Issue by Isaneefel** [Cuppycake/Mech-and-Magic#30]
I have a crucible flush in the ground. i am using glowstone nooks on all 4 corners to hold in the Flux. When i place water on the nooks it duplicates my bucket and it stays around even when i relog.

**Comment by Cuppycake** [comment]
Was not able to reproduce at your base. Any more details? Vanilla bucket?

**Comment by Isaneefel** [comment]
Yes it was a Vanilla bucket.  I noticed the new buckets after i pick up the water block again.
