### ISSUE TITLE
crashing due to "unknown" item 

### ISSUE THREAD

**Issue by matthew1123244** [Cuppycake/Mech-and-Magic#35]
i was on the public server about 2 hours ago then left because i had to go do other stuff then when i got on 20 minuets or so ago and tried to acces my me system it crashed me ... i have done some troubbleshouting and figured out it was in my drives and not the dsu's but i have 160 drives soo its hard to figure out which one it is please help heres the crashlog      
http://paste.atlauncher.com/view/66a253d5  if you can help thanks if not then i guess i can do what i can

**Comment by Cuppycake** [comment]
Any logistics pipes involved in your setup?

**Comment by matthew1123244** [comment]
yes but they were fine before i left so the first time

**Comment by Cuppycake** [comment]
Have you tried removing them?

**Comment by matthew1123244** [comment]
i cant the second i try to enter my me system it instantly brings me to the home screen makes no diffrence what way i enter my system

**Comment by matthew1123244** [comment]
do you know of a way to extract all of a mod from a me system? and if so i could pull all of logi pipes into a trash bin without any care

**Comment by Cuppycake** [comment]
Have you tried process of elimination by making another system or ME chest and checking one drive at a time?

**Comment by matthew1123244** [comment]
not yet but the problem is that i have 160 drives so its kind of dificult to

**Comment by Cuppycake** [comment]
Well you dont have much of an option lol. Im certainly not gonna do it. lol.

**Comment by matthew1123244** [comment]
ok ill figure it out

**Comment by matthew1123244** [comment]
this may take an hour or so

**Comment by matthew1123244** [comment]
i have found the four drives that are crashing me

**Comment by matthew1123244** [comment]
that took significantly less time than i thought
