### ISSUE TITLE
ars magika enchants

### ISSUE THREAD

**Issue by NalyKalZul** [Cuppycake/Mech-and-Magic#38]
ok just removed the old of this ticket info after doing some research.
i now can confirm 100% it's is my leggings with the dispel enchant from ars magika2 .

**Comment by usmc-Blockhead** [comment]
so what he is asking for you to do is take off his pants.......LOL!

**Comment by Cuppycake** [comment]
>.>

**Comment by NalyKalZul** [comment]
still unable to join.

**Comment by Cuppycake** [comment]
Log in again @NalyKalZul

**Comment by Cuppycake** [comment]
Poke me when you get into TS next and Ill try to get the armors off you.
