### ISSUE TITLE
Crash on wearing Water Orbs from AM2 and submersing in water

### ISSUE THREAD

**Issue by Treazul** [Cuppycake/Mech-and-Magic#4]
Upon equipping the water orbs rare drop from the Water guardian and diving into the water the game crashes with the following error; http://pastebin.com/tQhXNKni then on subsequent loading of the world the game will crash once more with the following error; http://pastebin.com/GNdWJpLd

**Comment by Treazul** [comment]
Crashes upon world load persist even with update.

**Comment by Cuppycake** [comment]
On the server?

**Comment by Treazul** [comment]
No, on a single-player world. If you need a copy of the world file I can get that

**Comment by Cuppycake** [comment]
Nope. On the server we ran into it once or twice and simply teleporting the player out of the water helped. If you can somehow get your player out of it that should fix it for you for the moment.
