### ISSUE TITLE
crashing in 2.2.20-4

### ISSUE THREAD

**Issue by tengdahuang** [Cuppycake/Mech-and-Magic#41]
It was always crashing when i use this seed: -1542702863

**Comment by Cuppycake** [comment]
While Id like to simply say...dont use that seed. Im interested in seeing why it happened. Can't speculate anything until you provide me a crash report.

**Comment by tengdahuang** [comment]
I don't know why, when i'm using my home computer it crashed, but in my working computer it works. There was crash report but i didn't saved it. I remember it was dark iron ore gen.
like this http://forum.feed-the-beast.com/threads/factorization-crash-dark-iron-ore-seems-to-be-the-cause.37940/

**Comment by Cuppycake** [comment]
I wont use a crash report from another modpack to speculate an issue with this one.
