### ISSUE TITLE
magical crops update request 

### ISSUE THREAD

**Issue by matthew1123244** [Cuppycake/Mech-and-Magic#44]
an update to magical crops is due and with a new version theres a bunch of awsome new stuff heres the link to the update http://minecraft.curseforge.com/mc-mods/232150-magical-crops-core/files/2245371 i have tested it out and its not a bad update

**Comment by Cuppycake** [comment]
This Github is not for suggestions or mod updates. I watch the mods daily and watch for updates. Please keep this for bug reports only.
