### ISSUE TITLE
fov problems,lost my bag trying to fix it

### ISSUE THREAD

**Issue by NalyKalZul** [Cuppycake/Mech-and-Magic#45]
so since a more recent patch i am unable to play due some fov changes,which makes my motion sick rather quickly,so i decided to attempt suicide by the sacrificial knife.
i thought it might have been a speed buff spell i made that caused it but those value's should if they get stuck get reset by a death.
and in the process i lost my 52 slots nearly packed "soulbound I" bottomless bag,and the sickening fov problem persist.

please tell me you can regain that bag for me as i had some projects lined up to play with,not to mention some of my tools and very rare items i lost inside that bag.

![2015-07-04_01 02 31](https://cloud.githubusercontent.com/assets/12812081/8505550/772be30a-21e9-11e5-9fef-7350aac46c44.png)

**Comment by Cuppycake** [comment]
Why would you experiment holding valuable items lol. Did a grave not spawn?

**Comment by NalyKalZul** [comment]
i know how the enchant works,any marked items,similar to how some plugin works outside of the extra utility graves move them into a temp file to be moved back into the play inventory data.

i was surprised to easily it move my baubles,and knapsack(the tinkers equiped bag) back into place.
normally the knapsack if dropped to death trow the items all over the place.

the only thing i could think of was the sacrificial knife being cloned and pushing it out of my inventory somehow when the temp file was trying to put everything back.
the items are put back on the exact inventory slot id they where on death.

**Comment by Cuppycake** [comment]
IDK what this post is about or what you are trying to convey to me lol.

**Comment by NalyKalZul** [comment]
still got the fov problem,even with al my gear dropped my speed is still far above normal.

i think the buff spell i made with ars magika 2 some permanently changed my stats persisting through death.
probably the result of the buff spell i made was..speed 6 modifier which basically puts you in the permanent running focus state.
but if i move at all the game thinks i am trying to run and again trows a other layer of that running fov focus,and it keeps flickering graphically between the two states when i move at all.

i've suicided several times,try to gain some speed modifiers and purge them with milk or other means then suicide,but it keeps coming back.
