### ISSUE TITLE
Magical crops are missing

### ISSUE THREAD

**Issue by usmc-Blockhead** [Cuppycake/Mech-and-Magic#46]
so I know the log says "now modular" but not sure what that means......when I log on my magical crops seeds are missing, my stored essences are missing, my armor is missing, anything made with magical crops is gone.......what does this all mean?  I see the mod is still in the mod list, so I don't think it means you are scrapping the mod, but I really hope my stuff is not lost.

**Comment by Cuppycake** [comment]
The mods aren't going anywhere. Magical Crops is still an extremely BETA mod. This is Magical Crops Beta 4 so it seems hes changed the mod significantly.

**Comment by usmc-Blockhead** [comment]
okay so do we have to start over.....or is there a chance of our stuff coming back.

**Comment by Cuppycake** [comment]
Sorry but it doesn't look like it's coming back :/ idk what he changed or why he did it the way he did.  I'll double check tonight.

**Comment by NalyKalZul** [comment]
i noticed one of my barrels retained some of the amount i had,so when i put one it it immediately  jumped back to having only 448 stacks of the stuff.
i hate the new low tier stones,the thermal cyclic assemblers don't like the meta data they work with:(
