### ISSUE TITLE
extra utils portal not working and a fix to it 

### ISSUE THREAD

**Issue by matthew1123244** [Cuppycake/Mech-and-Magic#49]
so i went searching to find out why the extra utils portals arent working and it due to the dimension id's of galicticraft overlapping with the extra utils id's so all that is needed is to change the id's ( i dont know how hard that will be but its the only real option)

**Comment by Cuppycake** [comment]
Even on the official server right now?

**Comment by matthew1123244** [comment]
yes ... ive tried going into them in survival and creative in a single player and last time i had tried on the official server it didnt work either
