### ISSUE TITLE
NEI "u" glitch

### ISSUE THREAD

**Issue by Devexia** [Cuppycake/Mech-and-Magic#50]
When I press U to see what an item can craft, that make my game freeze for a long minute, and in rarest ocasions it crash :/ Is there a way to fix that?

**Comment by matthew1123244** [comment]
this also happens to me

**Comment by Cuppycake** [comment]
This is usually just some lag with the massive amount of items it has to filter on request.

**Comment by Cuppycake** [comment]
Ill be doing a larger update this weekend with updated versions of NEI and NEI addon mods so we shall see if that helps.

**Comment by matthew1123244** [comment]
will you be adding a nei addon for thaumcraft ? it would be verry usefull

**Comment by Devexia** [comment]
Awesome!:D

**Comment by Cuppycake** [comment]
Anyone seen any better performance now?

**Comment by Devexia** [comment]
I'll try today!^^

**Comment by Devexia** [comment]
It works fine, thank you!:D
