### ISSUE TITLE
Server lag

### ISSUE THREAD

**Issue by usmc-Blockhead** [Cuppycake/Mech-and-Magic#54]
the lag on the server has been pretty bad the last day or so.  everyone in TS has been feeling it to the point were they get mad at people for exploring the map......what fun is minecraft without exploring.

**Comment by Cuppycake** [comment]
Well those that are that unhappy can leave if they like.  No one knows the cause of the lag and it shouldn't be over world exploration.  I'll look into it tonight.

**Comment by usmc-Blockhead** [comment]
I was just trying to help, sorry

**Comment by Cuppycake** [comment]
No don't be sorry :)  just saying.  I'll check it out.
