### ISSUE TITLE
Player Interface crash?

### ISSUE THREAD

**Issue by Isaneefel** [Cuppycake/Mech-and-Magic#57]
The server is crashing when i try to login. The only thing i have made recently is a player interface block from random things. I put it into the world and interacted with it. Since i needed to research it more i picked it up and put it into my AE system.  The sever went down a few minutes later. Now when i tried to login tonight it crashed the server several times. That is the only thing i have that hasnt been around for several days at least.

**Comment by Cuppycake** [comment]
Working on it now.

**Comment by Cuppycake** [comment]
This has been resolved @Isaneefel?

**Comment by Isaneefel** [comment]
Its fixed. made sure to trashcan that block just to make sure.
