### ISSUE TITLE
tinkers book not readable

### ISSUE THREAD

**Issue by usmc-Blockhead** [Cuppycake/Mech-and-Magic#61]
I made the book materials and You volume 2, and most of the letters are messed up, tried on vanilla table, crafting station, and the crafting grid of the ME, so all places
![tinkers](https://cloud.githubusercontent.com/assets/12266272/9568256/15f194e4-4ef9-11e5-9d3d-81c680c343bb.PNG)

**Comment by Cuppycake** [comment]
Known issue. Slight manual fix but I dont want to distribute a modified jar. Ill keep an eye out for a version fix.

**Comment by usmc-Blockhead** [comment]
thanks you.....cause it would be really nice to be able to look at the book for info about tool parts and modifiers.
