### ISSUE TITLE
error creating/launching new world in singleplayer

### ISSUE THREAD

**Issue by BioWulfas** [Cuppycake/Mech-and-Magic#63]
i launch the game, ( no additional mods installed)
go to single player
create or launch new world
world is loading.....
for a second i see main menu window
minecraft goes to not responding
game crashes and i am back at launcher

this is copy of log i found in ATlauncher console 

http://pastebin.com/X1L4YnYd

**Comment by Cuppycake** [comment]
Doesn't have the crash report in it. I need the latest report from the crash-reports folder.

**Comment by BioWulfas** [comment]
cant find similar report that vanila generates, even cant find crash-reports folder in ATlauncher folder. in Appdata only old vanila reports.
found strange report but i dont think this is what you are looking for

http://pastebin.com/J9m8rXpD

whats strange, that i played single player like 15min, then reloaded game and i wasnt able to launch any world since

**Comment by BioWulfas** [comment]
i am sorry i am so bad at this.... i know you are busy man and i feel bad that i bother you :/

**Comment by Cuppycake** [comment]
Did you recently update your java?


Alls you need to do is go to your instance in ATL, click Open Folder, Then click on crash-reports.

**Comment by BioWulfas** [comment]
![where is crash](https://cloud.githubusercontent.com/assets/14169541/9737552/d7aaa5f0-564f-11e5-9283-48ba3c0e68eb.jpg)
 no i didnt, going to try reinstall it, maybe it will work
