### ISSUE TITLE
Question: Downgrade Pack update?

### ISSUE THREAD

**Issue by BBgun38** [Cuppycake/Mech-and-Magic#65]
I just noticed that changelogs on the site and the Minecraft Pack Versions have taken off -4.  Is it because of a bug of some kind? Or did mods not mesh well w/ FastCraft? (not important just can't find info on how to reach you for questions)

**Comment by Cuppycake** [comment]
To many issues in recent versions so I downgraded for max stability while I work on the dev version

**Comment by BBgun38** [comment]
K, thanks for the update, just wondering why it was downgrading. Would you rather me post minor questions here or on someother site?

**Comment by Cuppycake** [comment]
Ourgamingnetwork.com or Twitter

**Comment by BBgun38** [comment]
what would be the twitter info? i just made an account because i thought that would be your perfered spot for questions

**Comment by Cuppycake** [comment]
@MechandMagic

**Comment by BBgun38** [comment]
Ty closing this issue now.
