### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by eethompson** [Cuppycake/Mech-and-Magic#66]
http://pastebin.com/3t8Vxbi4

**Comment by Cuppycake** [comment]
For the love of god pastebin. And information. Details.

**Comment by eethompson** [comment]
http://pastebin.com/3t8Vxbi4

**Comment by Cuppycake** [comment]
After the fact doesnt help. I need details when does this happen, how many times has it happened, etc.

**Comment by eethompson** [comment]
This is no longer an issue , I swiped the pack and re downloaded it
