### ISSUE TITLE
Cresote oil fluid dictionary

### ISSUE THREAD

**Issue by TriffidDK** [Cuppycake/Mech-and-Magic#67]
Bucketing railcraft cresote oil from any tank or coke oven produces the immersive engineering creosote that doesn't work for railcraft recipes. (like wooden ties)

**Comment by Cuppycake** [comment]
@TriffidDK is crafting possible if the oil is in a carpenter?

**Comment by Cuppycake** [comment]
Until the mod authors talk to each other better I have made alternate recipes. 1 bucket of IE creo oil will give 1 bucket of RC creo oil. Same for the bottles.
