### ISSUE TITLE
greif prevention bugged up

### ISSUE THREAD

**Issue by NalyKalZul** [Cuppycake/Mech-and-Magic#68]
so poked my head back on the server a few days ago,and got a tiny head start done already,and i just got on and noticed my home got re-rolled to older position while i was scouting on the first day.

![2015-09-12_02 46 10](https://cloud.githubusercontent.com/assets/12812081/9829084/cba9cc8a-58f8-11e5-8c6f-a6cb11564500.png)

and yea my claim blocks is now negative -6.5k my first plot shows up buggy, and when i plopped down a chest i got the starter bonus of claimed land,which my initial plot already got once.

wtf is going on with greif prevention?

**Comment by Cuppycake** [comment]
Basically...Its a 1.7.9 plugin, running on 1.7.10 server, running a completely modified .jar, running alongside mods. These things happen. 

As far as claims being removed or altered. You probably weren't logged on for long enough and the claim got pruned and deleted.

**Comment by NalyKalZul** [comment]
ok thank you.
