### ISSUE TITLE
Mana bug

### ISSUE THREAD

**Issue by usmc-Blockhead** [Cuppycake/Mech-and-Magic#7]
Mana flowers are disconnecting from the spreaders and stop flowing the mana to the pools.  You can reconnect the flowers with the wand once you catch the problem.  But they will disconnect again at a later time.  I went to Naly's house to see if he had the problem, and he did not have it, but then this morning he yelled at me for breaking his flowers, because they had disconnected as well.

**Comment by Cuppycake** [comment]
Nothing else in the chunks are being affected? If you place a block and leave the chunk do the changes made still stick?

**Comment by usmc-Blockhead** [comment]
nothing else in the chunk is affect only the flowers.

**Comment by TriffidDK** [comment]
All my mana flowers did as well this sunday. Only happened once though. 
The timing seemed a bit random, just about no changes the day it happened and absolutely no changes in my botania setup in a long time.

**Comment by TriffidDK** [comment]
Happened quite a few times now. they seem to simply forget their binding when unloaded

**Comment by Cuppycake** [comment]
This could probably be something with Cauldron and forge chunkloading. Will watch for updates.

**Comment by usmc-Blockhead** [comment]
Hey I have an update......last few days I was having lines of my ME system disappear.  I first thought people were messing with me (but for fun)  but after a few times, I killed all trust permissions cause it was only funny a few times... and it was still happening.  So I asked around, and everyone said don't use the glass flux cable it can do that, so I changed the line to smart cable and it is still disappearing in the walls near the botania area of my base.  Hope that helps, feel free to come take a look, I built a service tunnel for the cable since it was breaking so often, made it easier to fix.  Oh and if I leave the world and come back it will most defiantly be broken when I return, so I think you might be on the right track when you say chunk loading issues.

**Comment by Cuppycake** [comment]
vaskii is trying a fix for this in the newest dev version for version 192.

**Comment by Cuppycake** [comment]
Can we check this out again and confirm if its still happening with the newest version in yesterdays update?

**Comment by Cuppycake** [comment]
@usmc-Blockhead

**Comment by TriffidDK** [comment]
Just tested. still bugged. All my flowers just lost their binding on chunk unload.

**Comment by Cuppycake** [comment]
Alright from the sounds of other responses on the issue I made on their github its looking like build 193 might mix this.
