### ISSUE TITLE
Recipe: Chisel 2 chisel

### ISSUE THREAD

**Issue by TriffidDK** [Cuppycake/Mech-and-Magic#70]
The chisel 2 mod's chisel seems to have reverted back to old recipe which conflicts with Furniture mods knife.

**Comment by Cuppycake** [comment]
But not on single player?

**Comment by TriffidDK** [comment]
same in singleplayer

**Comment by TriffidDK** [comment]
Well in the new -1 beta the chisel simply do not have a recipe

**Comment by Cuppycake** [comment]
Well chisel just updated 11 minutes ago so a id probably changed. We'll kind of be in a beta mode for a few days.
