### ISSUE TITLE
Missing mods

### ISSUE THREAD

**Issue by BBgun38** [Cuppycake/Mech-and-Magic#73]
when i wanted to join the server it said:

Mod rejections [FMLMod:aura{unspcified}, FMLMod:StorageDrawers{1.7.10-1.6.1}, FMLMod:witchery{0.24.1}, FMLMod:BiblioCraft{1.11.1}]

Does that mean i have more mods then the server, or does it mean the server has more mods then Beta-5 have? (Beta-4 has even more when i try to join the server)

**Comment by Cuppycake** [comment]
Switch to master server on the ATL and download the beta 6

**Comment by Cuppycake** [comment]
All should be normal now. Use whatever server or Auto.
