### ISSUE TITLE
login crashing

### ISSUE THREAD

**Issue by cobaltbunny** [Cuppycake/Mech-and-Magic#76]
http://pastebin.com/p5405D4a

**Comment by Cuppycake** [comment]
Details of what occurred during the crash. Any reason to believe its your inventory or your chunk? So far chunk backups from the past 3 days are not working. 

You should always provide as many details as you can when leaving a crash report.

**Comment by cobaltbunny** [comment]
Sorry, I was mining last time I was on. Nothing really advanced in my base to cause a problem. It just dumps me out when I get to the point where I am entering the world.

**Comment by cobaltbunny** [comment]
Cuppy, If you want to clear everything I have on me, to see if that works, feel free. Nothing that can't be remade.

**Comment by Cuppycake** [comment]
player data cleared

**Comment by cobaltbunny** [comment]
Now I am getting the errors "Disconnected from server" and "A fatal error has occured, this connection is terminated" After this happened the first 4 tries or so, I selected reinstall before logging on. I am still getting the messages.
