### ISSUE TITLE
Golemancer's Bell crafting crashes client.

### ISSUE THREAD

**Issue by NalyKalZul** [Cuppycake/Mech-and-Magic#77]
http://paste.atlauncher.com/view/dd088a68

i also noticed my old golemancer's bell was missing from two thaumcraft chest i have.

also noticed as i try to pull out the crafting recipe it called a Golemancer's Bell -1 for some reason

**Comment by Cuppycake** [comment]
Will be trying a fix for this during the week with modtweaker. The mod doesnt seem to be updating anymore.

**Comment by Cuppycake** [comment]
Fixed
