### ISSUE TITLE
inventory tweaks, single item quick hotkey (ctrl).

### ISSUE THREAD

**Issue by NalyKalZul** [Cuppycake/Mech-and-Magic#78]
since this morning i noticed that out of the blue that the inventory tweaks seems to be partially blocked server side somehow?
using ctrl hotkey to grab 1 item out of a stack when you need to quickly grab 3 or 4 pieces only no longer works.

tested it single player and it works fine,and quite a few people i asked also noticed this suddenly not working.
is the server being derpy,or is it disabled deliberately? to ea prevent server spamming query's or prevent a new kind of duplication bug?

**Comment by Cuppycake** [comment]
Absolutely nothing has been changed. Seeing as its a client side only mod I can promise nothing server side has been altered.
