### ISSUE TITLE
wand foci: Nine Hells

### ISSUE THREAD

**Issue by NalyKalZul** [Cuppycake/Mech-and-Magic#79]
like last season the grief prevention plugin is not letting me summon the hell bat inspired familiars.
![2015-09-30_11 48 12](https://cloud.githubusercontent.com/assets/12812081/10189897/5f21a8ce-6769-11e5-974f-ebe909de17b2.png)
![2015-09-30_11 48 18](https://cloud.githubusercontent.com/assets/12812081/10189896/5f1f62da-6769-11e5-9136-0a50745bd64b.png)

while 1 upgrade is made for the reason there probably on the default grief prevention list,i do see creepers and ghast about there respected dimensions,so why is the hell bat in particular on this list to start with?
there by default nether bound,but even there the foci isn't working.

**Comment by Cuppycake** [comment]
Honestly dude you need to stop assuming that everything has a list and things are on it and edited and changed blah blah blah. EVERYTHING in the plugin is by mod specific fake players being trusted in the claim. Try finding the fake player for the mod in question and trusting it in your claim.
