### ISSUE TITLE
mana beans are not food

### ISSUE THREAD

**Issue by NalyKalZul** [Cuppycake/Mech-and-Magic#80]
so was planning to set up a mana bean farm for some aspect,and blocky is also interested in it for easy salt generation that this can provide.
we found out the server somehow sees them as food,so we can even plant them >.< only nom them for weakness buffs.

**Comment by usmc-Blockhead** [comment]
still unable to plant the mana beans......the server thinks they are food instead.

**Comment by Cuppycake** [comment]
No found fix for this. Its not the server, its the mods...
