### ISSUE TITLE
Botania Gaia fight

### ISSUE THREAD

**Issue by NalyKalZul** [Cuppycake/Mech-and-Magic#83]
so recently started fighting the gaia boss again,and it nearly impossible to even get it started due this issue.
![2015-10-28_01 59 48](https://cloud.githubusercontent.com/assets/12812081/10777069/c565f13a-7d17-11e5-8537-7b46b9ec8dab.png)

i moved the damm thing around several times and still shows the same issue.
i have no clue why it suddenly doesn't want to work anymore.

"Edit" had to move it around several times to make it work again.
atm i don't know why is working in some places and not in others.

**Comment by Cuppycake** [comment]
Try again since the update

**Comment by Cuppycake** [comment]
Fixed since 4.1
