### ISSUE TITLE
Unable to log on

### ISSUE THREAD

**Issue by cobaltbunny** [Cuppycake/Mech-and-Magic#85]
Since the update, I have not been able to log on
Screen says Connection Lost     Mod rejections [FMLMod:BiblioCraft{1.11.3}, FMLMod:evilcraft{0.9.0}]

I have already deleted mech & magic and reinstalled it in my instances. This made no change

**Comment by MorikoNanami** [comment]
I have the same issue.

**Comment by Cuppycake** [comment]
Just because the pack updates does not mean the server has. Updates are not forced on the server and will not apply until the regularly scheduled restarts at 4, 8, and 12 EST.
