### ISSUE TITLE
Dub bug found

### ISSUE THREAD

**Issue by usmc-Blockhead** [Cuppycake/Mech-and-Magic#86]
here you go, I tossed the extra ingots in some lava, so I did not profit from this bug.   but if you take ore berries and craft them into ingots in the ME panel it keeps making stacks of 64 as long as you have the first 9 to fill the crafting boxes.  

![2015-11-07_06 47 13](https://cloud.githubusercontent.com/assets/12266272/11015694/7e1340d2-851c-11e5-8edc-0e09df40c68a.png)

**Comment by Cuppycake** [comment]
Can not reproduce
