### ISSUE TITLE
game crashing help!

### ISSUE THREAD

**Issue by usmc-Blockhead** [Cuppycake/Mech-and-Magic#87]
my blue backpack is crashing my game......when I try to access it and only, my game crashes, however here is the problem....I can tell you it is exactly in the backpack, and nico and cobalt can back me up (cobalt saw it just a week or so ago) but it will not narrow down what mod is causing the problem, cause that backpack is for all my tools, so there was tools in there from probably every mod and more.....

http://paste.atlauncher.com/view/78ee5152
[crash-2015-11-15_06.10.04-client.txt](https://github.com/Cuppycake/Mech-and-Magic/files/34878/crash-2015-11-15_06.10.04-client.txt)

you want to try rolling it back to a backup version of my backpack and then I will put the stuff in something new, since they have issues.  let me know, I think that would be easier, then trying to list all that was in there, but I can go through it and recreate new stuff with you if you prefer.

**Comment by Cuppycake** [comment]
There is no backup of your backup or player data. So thats out. Obviously its something from botania causing the issue in the bag or inventory. Can delete your player data and try to roll a inventory back using your last death point if its still in the files
