### ISSUE TITLE
Java Error 

### ISSUE THREAD

**Issue by PlazmaShadow09** [Cuppycake/Mech-and-Magic#88]
Here's The Error
Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host

If You Can Look Into Why This Happens Or If You Can Tell Me How To Fix This That Would Be Very Helpful. :D
Thanks
 - PlazmaShadow9

**Comment by Cuppycake** [comment]
This gives no information that is any bit useful.

**Comment by TheRoboFrog** [comment]
Plazma, you are a moron, I will have to attach a crash log for you

**Comment by TheRoboFrog** [comment]
This is plazma's log whilst running on my computer
[Plazma's Log.txt](https://github.com/Cuppycake/Mech-and-Magic/files/39823/Plazma.s.Log.txt)

**Comment by Cuppycake** [comment]
Still not very useful. When is this happening? Is it crashing to desktop? Is it when you touch a certain block. Need details.

**Comment by PlazmaShadow09** [comment]
When I Join I Fall Through The World And I Either Get One Of Two Things: I Get The Error I Mention Or I Time Out. Timing Out Isn't An Issue But It Is As Soon As I Load In The World It Get The Error

**Comment by Cuppycake** [comment]
this is most likely your connection to the server or your pc not being able to load into where you are.

**Comment by TheRoboFrog** [comment]
Is there some way to move his login ID area to another point, like his /home
