### ISSUE TITLE
minefactory reloaded planters

### ISSUE THREAD

**Issue by dsulkowska** [Cuppycake/Mech-and-Magic#95]
this is Tighearna, seems I crashed the server again. twice. by just placing the minefactory reloaded planer this time. earlier, it seemed linked to the platinum upgrades that I was trying to put on the harvester, but the planters worked fine for a while earlier; I don't know why suddenly everything crashes every time I log in, but it's probably these machines. I'll stay off the server until the issue is resolved, let me know what's up and if I can help somehow/if it's safe for me to log in

**Comment by Cuppycake** [comment]
should be fixed now. I saw it happen. It was that 3x3 planter. Get one  and remove it real quick.
