### ISSUE TITLE
Mod EvilCraft disabled reciepe

### ISSUE THREAD

**Issue by Shotman** [Cuppycake/Mech-and-Magic#96]
I don't know if it's the EvilCraft mod that disabled it or if it's in a bug in the modpack but the "Box Of Eternal Closure" is nowhere to be found ... I even tried to give it to me with the "evilcraft:boxOfEternalClosure" ID but doesn't work either

**Comment by Shotman** [comment]
I tried to enable it via the evilcraft.cfg file and puting the `B:boxOfEternalClosure=false` line to `B:boxOfEternalClosure=true`on both client and/or server but no one can connect to the server

**Comment by Cuppycake** [comment]
What is it telling users when they try to connect? 

Should only need to worry about configs on server side but knowing I did not change 
`B:boxOfEternalClosure=false `

I assume it is disabled by default for a reason. I will look into it.

**Comment by Shotman** [comment]
They have an error message at connection like : `Fatally missing blocks and items`
And I tried to modify the config on server side only or client and sever side or client only  and none of those options work
